github: [ayushsaxenagithub]
patreon: [ayushsaxenapatron]
open_collective: [ayushsaxenaoc]
ko_fi: [ayushsaxenakofi]
tidelift: [npm/ayushsaxena]
community_bridge: [ayushsaxenacb]
liberapay: [ayushsaxenaliberapay]
issuehunt: [ayushsaxenaissuehunt]
otechie: [ayushsaxenaotechie]
lfx_crowdfunding: [ayushsaxenalfx]
custom: ['link1', 'link2']
